---
title: "DATA1001 FAQ"
author: "USYD"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
description: "A public FAQ for DATA1001"
---

# Welcome {.unnumbered}

This book aims to be a FAQ repository for students taking **DATA1001** at the University of Sydney (USYD). It is not endorsed by USYD in any way -- all content is community-driven and open to the public. Contributions are made voluntarily. [What are the benefits](#contribute)?

**Note that this FAQ is for R and RStudio.** If you have other queries related to this unit, check Canvas or Ed. If you are not a DATA1001 student, some questions in the FAQ may not make sense.

# How do I use this book?

## If you are a student

-   This book is dividend into 3 main Parts: Install, Data visualisation, and Data wrangling. Click on the sections in the sidebar to the left to navigate to the specific FAQ item.
-   If available, subsections are listed on the sidebar to the right, at "On this page".

## If you are staff

-   You may want to contribute to, or edit content in this book. The best way is to fork this project on GitHub and make edits to *specific* sections. Try not to edit a whole bunch of stuff at once.
-   Alternatively, use GitHub issues to submit an Rmd file containing a full FAQ. The document will be incorporated into this book and credit will be provided.

# How do I report an error in this book?

Great work in detecting the problem! There are three ways:

1.  Post the issue on Ed.
2.  Submit an issue on this project's GitHub Issues page.
3.  For the adventurous, create a pull request on GitHub.

Please document the issue, and suggested fix (if any), appropriately.
